In [37]:
import numpy as np
import typing as tp

def find_nearest_points(A: np.ndarray, B: np.ndarray, k: int) -> np.ndarray:    
    B = np.expand_dims(B, axis=1);
    C = A-B;
    C = np.power(C, 2)
    C = np.sum(C, axis=-1);
    ind = np.argsort(C, axis=1)
    print(ind)
    return (ind[:, :k] + 1)

def find_nearest_points2(A: np.ndarray, B: np.ndarray, k: int) -> np.ndarray:
    dst = np.sum((A[:, np.newaxis] - B) **  2, axis=2)
    C = np.argsort(dst, axis=0);
    C = C[:k] +  1
    return C.T

In [38]:
A = np.array([
    [0, 0],
    [1, 0],
    [2, 0]
])

B = np.array([
    [0,1],
    [2, 1]
])


print(find_nearest_points(A, B, 2));
print(find_nearest_points2(A, B, 2));


[[0 1 2]
 [2 1 0]]
[[1 2]
 [3 2]]
[[0 2]
 [1 1]
 [2 0]]
[[1 2]
 [3 2]]
