In [8]:
import numpy as np
from tqdm.auto import tqdm

In [4]:
arr = np.arange(1, 9, 2);
print(arr)

[1 3 5 7]


**tqdm позволяет измерять время занимаемое итерацией**

In [6]:
print(arr.shape)

(4,)


In [9]:
for elem in tqdm(arr):
    print(elem);

  0%|          | 0/4 [00:00<?, ?it/s]

1
3
5
7


In [13]:
a = np.array([1, 10, 11, -2, 0, -3]);

In [15]:
print(a[a > 0])

[ 1 10 11]


In [17]:
a = np.full((3,3), 3, dtype=np.float32);
print(a)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [19]:
a = np.linspace(100, 500, 42);
b = np.logspace(2, 3, 21);

print(a);
print(b);

[100.         109.75609756 119.51219512 129.26829268 139.02439024
 148.7804878  158.53658537 168.29268293 178.04878049 187.80487805
 197.56097561 207.31707317 217.07317073 226.82926829 236.58536585
 246.34146341 256.09756098 265.85365854 275.6097561  285.36585366
 295.12195122 304.87804878 314.63414634 324.3902439  334.14634146
 343.90243902 353.65853659 363.41463415 373.17073171 382.92682927
 392.68292683 402.43902439 412.19512195 421.95121951 431.70731707
 441.46341463 451.2195122  460.97560976 470.73170732 480.48780488
 490.24390244 500.        ]
[ 100.          112.20184543  125.89254118  141.25375446  158.48931925
  177.827941    199.5262315   223.87211386  251.18864315  281.83829313
  316.22776602  354.81338923  398.10717055  446.68359215  501.18723363
  562.34132519  630.95734448  707.94578438  794.32823472  891.25093813
 1000.        ]


In [26]:
a = np.array([1,3,2])
b = np.array([4,6,10])

a = np.hstack((a, b))
print(a)
a = np.delete(a, 2);
print(a)

[ 1  3  2  4  6 10]
[ 1  3  4  6 10]


In [29]:
b = a[::-1]
b[0] = 12;
print(b)
print(a) #массив изменятется

[12  6  4  3  1]
[ 1  3  4  6 12]


In [36]:
arr = np.linspace(-3*np.pi,3*np.pi, 10, dtype=np.float64);
squares = np.sin(arr) ** 2 + np.cos(arr) ** 2 + np.exp(arr) ** 2;
print(np.all(squares >= 1))

True


In [38]:
prices = np.array([52000, 57000, 63500, 61500, 48000]);
prices_from_rielt = np.array([50000, 51000, 62500, 64500, 48000]);

print(np.sum(np.abs(prices - prices_from_rielt)) / prices.shape[0]);

2400.0


**Broadcasting**

In [39]:
a = np.array([1,2,3]);
print(a * [3])

[3 6 9]


In [42]:
a = np.array([1,2,3, 4]);
b = np.array([1,2,3]);
print(a.reshape(-1, 1) + b) #(4, 1) + (3)

[[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]
